# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_page1.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../nbs/00_page1.ipynb 11
class Card:
    "A playing card"
    def __init__(self,
                 suit,   # index to `suits`
                 rank):  # index to `ranks`
        self.suit,self.rank = suit,rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__
